#pragma once

#include "driver/gpio.h"
#include "driver/spi_master.h"
#include "hal/adc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BOARD_LCD_SPI_HOST SPI2_HOST
#define BOARD_LCD_PIN_NUM_RST GPIO_NUM_16
#define BOARD_LCD_PIN_NUM_SCLK GPIO_NUM_47
#define BOARD_LCD_PIN_NUM_DC GPIO_NUM_45
#define BOARD_LCD_PIN_NUM_CS GPIO_NUM_21
#define BOARD_LCD_PIN_NUM_MOSI GPIO_NUM_48
#define BOARD_LCD_PIN_NUM_MISO (-1)
#define BOARD_LCD_PIN_NUM_BK_LIGHT GPIO_NUM_40

#define BOARD_BUTTON_ADC_UNIT ADC_UNIT_1
#define BOARD_BUTTON_ADC_CHANNEL 7

#define BOARD_STATUS_LED_GPIO GPIO_NUM_46

#define BOARD_AUDIO_I2C_PORT I2C_NUM_0
#define BOARD_AUDIO_I2C_SDA GPIO_NUM_0
#define BOARD_AUDIO_I2C_SCL GPIO_NUM_1

#define BOARD_AUDIO_I2S_PORT I2S_NUM_0
#define BOARD_AUDIO_I2S_BCK GPIO_NUM_2
#define BOARD_AUDIO_I2S_MCK GPIO_NUM_3
#define BOARD_AUDIO_I2S_DI  GPIO_NUM_4
#define BOARD_AUDIO_I2S_WS  GPIO_NUM_5
#define BOARD_AUDIO_I2S_DO  GPIO_NUM_6

#define BOARD_AUDIO_PA_EN_GPIO GPIO_NUM_NC
#define BOARD_AUDIO_PA_EN BOARD_AUDIO_PA_EN_GPIO
#define BOARD_AUDIO_ES8311_ADDR 0x18
#ifdef __cplusplus
}
#endif
